### ISSUE TITLE
Downloaded OSAB Game Installer (Sims 2 Pack installer): It's saying the sims 2 isnt installed on my computer. 

### ISSUE THREAD

**Issue by Bluebirds123** [voicemxil/TS2-Starter-Pack#20]
**Describe the bug**
Every time I launch the sims 2 via RPC Via the Osab Game Installer. It's says the sims 2 isnt installed on my computer.  I thought this was the Ultimate Collection. Not Every pack - The sims 2 base game

**To Reproduce**
Steps to reproduce the behavior: Installed it as told to

**Expected behavior**
I expected it to launch the sims 2 with zero problems at all

**Screenshots**
If applicable, add screenshots to help explain your problem. The installer will print log messages to the "more details" box.

![2023-01-05-03-33-28](https://user-images.githubusercontent.com/122012049/210741983-f741be9e-dc5c-42ee-9eda-d2707e6762fa.jpg)

**Installer version:**
- version 9

**Comment by voicemxil** [comment]
This error is not a bug, it's simply an error with the touchup step. There is a fix for it in the FAQs on both the wiki and the Discord server. If that doesn't work, our support forums for game-related issues are in the Discord server!
