### ISSUE TITLE
No neighborhoods?

### ISSUE THREAD

**Issue by googleooer** [voicemxil/TS2-Starter-Pack#23]
The game installs and everything, but I've run into some issues.

- Launching Sims2RPC just doesn't work.
- The game only launches if I open it through Sims2EP9.exe or Sims2EP9RPC.exe
- When it launches and finishes loading, i have no neighborhoods to choose from. If I try to play the tutorial, the game crashes.

**Comment by voicemxil** [comment]
The issues page is for reporting bugs/issues within the Starter Pack/installer itself. The issues you mentioned are non-specific to the Starter Pack, but I would be happy to help you on the [Discord](https://discord.gg/ts2-community-912700195249197086). We also have volunteers active daily in the #ts2-support forum! :)
