### ISSUE TITLE
Add option for installing clean versions of Neighborhoods

### ISSUE THREAD

**Issue by Starmann** [voicemxil/TS2-Starter-Pack#30]
**Is your feature request related to a problem? Please describe.**
The Sims 2 was shipped in somewhat of a buggy state. Whereas the RPC fixes some annoying bugs which affect the user's quality of life, neighborhood corruption is a far more dire issue which can affect players' save files. Thus we should at the very least include cleaned default versions of neighborhoods.

**Describe the solution you'd like**
Include this as a setting on the installer. I'm not sure what level of granularity it should have. Should we make it a simple "yes, fix my neighborhoods" or "no, keep things vanilla"? Should we enable selected on a per-expansion level? On a per-neighborhood/subhood level?

**Describe alternatives you've considered**
It's debatable to what level of fixes should be involved.  Some of these cleaned neighborhoods include event and memory fixes. I'm curious to see what everyone else's opinion on this is.

**Comment by voicemxil** [comment]
It would definitely be possible to add a future update. It could have an overall checkbox to install all of them, which would simply download them and replace the originals. But it could also expand allowing each individual clean template to be toggle-able.

As far as the level of fixes go, I'd probably be open to missing memory fixes and things of that nature. But ones with more drastic changes such as relocating Bella Goth would probably be out of the question. I'll look into which templates are a good fit at some point.

**Comment by Starmann** [comment]
Notably my research indicated that every expansion except Bon Voyage added a hood that had some base level of corruption. Apparently the Vacation destinations don't have actual Sims with memories and stuff.

**Comment by Starmann** [comment]
# Basegame

1. https://modthesims.info/d/666585/clean-pleasantview-without-bella-goth.html
2. https://modthesims.info/d/641841/fixed-maxis-strangetown.html
3. https://modthesims.info/d/669460/clean-veronaville-with-fixed-scripted-events.html

In my search these came out as the cleanest most source-accurate versions of the basegame hoods. At least Pleasantview and Veronaville appear to be based off MeetMeAtTheRiver's clean versions of neighborhoods.

**Comment by Starmann** [comment]
# Subhoods

https://modthesims.info/d/672391/fixed-maxis-universities-reupload.html

https://meetme2theriver.livejournal.com/110658.html

https://modthesims.info/d/666124/clean-bluewater-village-with-all-townies.html

As mentioned previously, BV subhoods are already clean

**Comment by Starmann** [comment]
# Stealth Hoods

https://meetme2theriver.livejournal.com/63030.html

MeetMe2TheRiver's clean Stealthhood templates appear to not have any of the problems a lot of their basehoods have. Often times they'll just delete townies.

**Comment by Starmann** [comment]
# Neighborhoods added by later expansions
1. https://modthesims.info/d/665908/clean-riverblossom-hills-with-townies-and-npcs.html
2. https://modthesims.info/d/666091/clean-desiderata-valley-with-townies-and-npcs.html
3. https://theneonplumb.tumblr.com/post/656712498541723648/clean-template-belladonna-cove-with-townies
