### ISSUE TITLE
scanned file through virustotal and came up as malware

### ISSUE THREAD

**Issue by jellie-bean** [voicemxil/TS2-Starter-Pack#40]
scanned downloaded file through virus total and come through as malware: W32.AIDetectMalware.64

**To Reproduce**
1.download suggested windows installer file
2.scan file through virustotal
3. W32.AIDetectMalware.64 detected

**Comment by voicemxil** [comment]
This is not a bug, "W32.AIDetectMalware" is a false positive that seems to affect most NSIS-based installers I tested. it could be due to one of the plugins used or due to the nature of extracting compressed files & running interpreted code, so unfortunately there is nothing I can do about it.
