### ISSUE TITLE
13.1 rev 1 32-bit?

### ISSUE THREAD

**Issue by vanyasem** [voicemxil/TS2-Starter-Pack#41]
https://github.com/voicemxil/TS2-Starter-Pack/releases/tag/v13.1

Would it be possible to provide a 32-bit executable for v13.1 rev 1? For use on Windows XP SP 3 x86

**Comment by voicemxil** [comment]
There is a 32-bit executable, but the version of Graphics Rules Maker used requires Windows 10 or later. A fallback version of GRM for older Windows version will be included in the next update, but you can still use version 12 in the meantime which has GRM 2.0.0.
