### ISSUE TITLE
won't let me download webinstaller.

### ISSUE THREAD

**Issue by concernedsimmer** [voicemxil/TS2-Starter-Pack#46]
when I click on the link for the web installer it begins to download then i get an error message saying it "isn't commonly downloaded" and "to make sure I trust this site." but when I mark the site as safe and go through the verification prosses for it will still not let me download the web installer

**Desktop (please complete the following information):**
 - OS:  windows
 - Browser Microsoft edge

**Additional context**
i am not very bright with computer related stuff at all.

**Comment by voicemxil** [comment]
You need to choose "keep"/"keep anyway" instead of "report as safe"
