### ISSUE TITLE
Confusion downloading DXVK

### ISSUE THREAD

**Issue by awesomedon** [voicemxil/TS2-Starter-Pack#47]
I downloaded the Starter Pack with the Web Installer, and chose to download DXVK in the menus because I run AMD Ryzen 5 5600 with Radeon graphics, and Vulkan ran successfully. The problem is, when I went to the TSBin files and created the text document, when I went to save it to TSBin, it alerted me that there was already a file with the same name "dxvk.conf", so it wouldn't allow me to save it without replacing the old file. One look at the old file lets me know that it is important information, so I'm not sure what to do. Should I add the required code to the pre-existing file, or am I just doing something wrong?

On another note, when I try to run the RPC, it says I don't have the compatible graphics drivers, which I'm not sure what to do about, since I updated my graphics driver prior to installation. I know next to nothing about graphics though, so I could have just done something wrong in that department :/
![Screenshot 2024-01-27 111947](https://github.com/voicemxil/TS2-Starter-Pack/assets/157905191/7b1fda3f-7ee0-49d4-8a0c-62d78559c08f)
![Screenshot 2024-01-27 112038](https://github.com/voicemxil/TS2-Starter-Pack/assets/157905191/167dae90-2fed-4824-9e32-c00bcb3e9531)

**Comment by awesomedon** [comment]
Here's a screenshot of what the RPC does.
![Screenshot 2024-01-27 112206](https://github.com/voicemxil/TS2-Starter-Pack/assets/157905191/a1dfac81-f1ca-4861-9cc7-b177a46239cc)

**Comment by voicemxil** [comment]
You can use CTRL+F to search for the line you need to modify in the existing conf file.

The DirectX 9 error might indicate GRM wasn't applied properly but also might be because you're running in fullscreen, which has some issues especially with DXVK. If you switch to windowed or borderless mode in RPCSettings, that may resolve it.

**Comment by awesomedon** [comment]
> You can use CTRL+F to search for the line you need to modify in the existing conf file.
> 
> The DirectX 9 error might indicate GRM wasn't applied properly but also might be because you're running in fullscreen, which has some issues especially with DXVK. If you switch to windowed or borderless mode in RPCSettings, that may resolve it.

Thank you for the help on the DirectX 9, I figured that out earlier haha. And I found the code in the pre-existing conf file, thanks! I had to look for it manually because I previously was using the search feature, but for whatever reason it wasn't showing up. Everything works perfect now! Thanks ^_^
