### ISSUE TITLE
Have a language selector before installing

### ISSUE THREAD

**Issue by MrArdillo** [voicemxil/TS2-Starter-Pack#49]
Is there a form to add a language selector before installer to avoid going to the registry editor after installing? (I do this to change from English, the language that installs by default for Spanish)

**Comment by voicemxil** [comment]
It’s intended to detect the system language based on the locale, but it might not always work and could fall back to English.

You don’t have to manually go into the registry editor, there are .reg files included in the “The Sims 2 Starter Pack\_Language Selection” folder that automate it for you, you just have to double click.

**Comment by Remzi1993** [comment]
> It’s intended to detect the system language based on the locale, but it might not always work and could fall back to English.
> 
> You don’t have to manually go into the registry editor, there are .reg files included in the “The Sims 2 Starter Pack\_Language Selection” folder that automate it for you, you just have to double click.

Would be nice to mention this in the readme or Google Doc: The Sims 2 Setup Guide

**Comment by MrArdillo** [comment]
Or add an option on the installer if someone wants to install it on another language or they are using Linux and it detects English as default

**Comment by voicemxil** [comment]
> Would be nice to mention this in the readme or Google Doc: The Sims 2 Setup Guide

True, but the installer does open the main folder after it completes  with the Language Selection being the very first option

**Comment by voicemxil** [comment]
> Or add an option on the installer if someone wants to install it on another language or they are using Linux and it detects English as default 

The language selector built-in to NSIS/MUI is for changing the installer language itself, which isn't translated. It's possible in the future but would require a custom dropdown/page in order to do it before install.
