### ISSUE TITLE
Not all expansions available 

### ISSUE THREAD

**Issue by loliman** [voicemxil/TS2-Starter-Pack#52]
Hi,

After installing via Web Installer and starting the game not all expansions seem to be working. H&M, Pets and more stuff seem to be missing from the game.

Am I doing something wrong?

Kind regards!

**Comment by voicemxil** [comment]
All expansions are included, they're in the collection versions (Fun with Pets, Best of Business, University Life) as it's the Ultimate Collection. if they're not showing up in-game or are missing from those folders then you would have likely had a download/extract error along the way. You can download individual packs from [here](https://github.com/mintalien/The-Puppets-2-Definitive-Edition/releases/tag/v12) to your Starter Pack folder if necessary
