### ISSUE TITLE
Web installer downloads old versions v12 instead of v13.2

### ISSUE THREAD

**Issue by Remzi1993** [voicemxil/TS2-Starter-Pack#64]
Your installer downloads v12, it should download the latest versions from: https://github.com/mintalien/The-Puppets-2-Definitive-Edition/releases (at this writing [v13.2](https://github.com/mintalien/The-Puppets-2-Definitive-Edition/releases/latest))

Use: https://github.com/mintalien/The-Puppets-2-Definitive-Edition/releases/latest (if you use "/latest" you will always get the latest release)

`Create folder: C:\Program Files (x86)\The Sims 2 Starter Pack\temp
Downloading Apartment Life from https://github.com/mintalien/The-Puppets-2-Definitive-Edition/releases/download/v12/ApartmentLife.v12.7z. Closing the download window will interrupt the download.
Apartment Life download status: OK
Extracting Apartment Life from temp\ApartmentLife.7z...
Delete file: temp\ApartmentLife.7z
Cleanup result: OK
Downloading Best of Business from https://github.com/mintalien/The-Puppets-2-Definitive-Edition/releases/download/v12/BestofBusiness.v12.7z. Closing the download window will interrupt the download.
Best of Business download status: OK
Extracting Best of Business from temp\BestofBusiness.7z...
Delete file: temp\BestofBusiness.7z
Cleanup result: OK
Downloading Bon Voyage from https://github.com/mintalien/The-Puppets-2-Definitive-Edition/releases/download/v12/BonVoyage.v12.7z. Closing the download window will interrupt the download.
Bon Voyage download status: OK
Extracting Bon Voyage from temp\BonVoyage.7z...
Delete file: temp\BonVoyage.7z
Cleanup result: OK
Downloading Base Game from https://github.com/mintalien/The-Puppets-2-Definitive-Edition/releases/download/v12/Base.v12.7z. Closing the download window will interrupt the download.
Base Game download status: OK
Extracting Base Game from temp\Base.7z...
Delete file: temp\Base.7z
Cleanup result: OK
Downloading Double Deluxe Packs from https://github.com/mintalien/The-Puppets-2-Definitive-Edition/releases/download/v12/DoubleDeluxe.v12.7z. Closing the download window will interrupt the download.`

**Comment by voicemxil** [comment]
No, it should not. This is intentional.
