### ISSUE TITLE
Unattended install

### ISSUE THREAD

**Issue by tannisroot** [voicemxil/TS2-Starter-Pack#9]
It would be lovely if there was an unattended option for this installer. With installable options configurable too

**Comment by voicemxil** [comment]
While this is more of an idea than an issue, I do plan on implementing highly requested features in the next release (v8, which will also be a full rewrite of the installer), after the existing functionality is added! :)

I can definitely make the component selection screen optional and simplify the installer itself. However, users will likely still need to configure Graphics Rules Maker separately.

**Comment by tannisroot** [comment]
Thanks! I don't really need GRM personally, just the sims 2 part, I just want to automate installation on Linux thus why I asked for unattended :)

**Comment by voicemxil** [comment]
Yes, basically everything can be toggled in the next release and users can choose between a full, minimal w/o fixes, or customized installation.
